# database/docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ai-viz-postgres
    environment:
      POSTGRES_DB: vizpoc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d vizpoc"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local